project:
  type: website
  output-dir: docs/
website:
  title: "Sterile inflammation"
  site-url: /sterile_inflammation/docs
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Analysis"
        menu:
          - text: "Empty droplets"
            href: analysis/01_empty_droplets.html
          - text: "Quality control"
            href: analysis/02_quality_control.html
          - text: "Clustering"
            href: analysis/03_clustering.html
  #       - text: "Marker genes"
  #         href: 04-marker-genes.html
  #       - text: "PAGA"
  #         href: 05-paga.html
  #       - text: "Cell velocity"
  #         href: 06-velocyto.html
  #   - text: "Reports"
  #     menu:
  #       - text: "Cell Ranger"
  #         href: cellranger_web_summary.html
  #   - text: "Methods"
  #     href: 90-methods.html
  # right:
  #   - text: "License"
  #     href: license.html
  #   - icon: fa-github
  #     href: https://github.com/lazappi/phd-thesis-analysiswebsite
format:
  html:
    embed-resources: false  # or true if you want them in a single HTML file
    self-contained: false   # ensures separate resource folders
    # This is the key:
    resource-paths: ["analysis"]
    theme: Default
    css: styles.css
    toc: true
    code-fold: true
    smooth-scroll: true
editor: source





