---
title: "About"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

# Sterile inflammation

This repository displays the analysis code and results for the sterile inflammation project in collaboration with Dr. Shweta Tikoo at the Deaprtment of Dermatology at the MedUni Wien.

The project aims to define changes in transcriptional landscape of stromal cells and leukocytes post sterile inflammation. These cells coordinate the recruitment of diverse immune cell subsets from circulation to the inflammed tissue to restrict inflammation and promote tissue repair.

The samples consist of FACS sorted cells from murine cremaster tissue under homeostasis or post-TNFa treatment at two different time points. The cells were then sequenced after cDNA libraries preparation.

The analysis shown here focuses on the decisions that were made during analysis and demonstrates a range of tools that can be used for various tasks.

To see the results of the analysis please visit the [analysis website](https://nami2309.github.io/sterile_inflammation "Analysis website"). If you wish to reproduce the analysis follow the instructions on the Getting started page.

The code in this analysis is covered by the [MIT license](https://choosealicense.com/licenses/mit/ "MIT License") and the written content on this website is covered by a [Creative Commons CC-BY](https://creativecommons.org/licenses/by/4.0/ "CC-BY License") license.

The publications mentioned and datasets used are covered by their respective licenses and usage agreements. Please refer to those sources for details.
